# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Read in the dataset

In [2]:
df = pd.read_csv("./fifa21 raw data v2.csv", low_memory=False)

df.sample(10)

ID           Name              LongName  \
17329  258152     N. Igbokwe  Nmadi-Morris Igbokwe   
11181  199768     C. Gartner     Christian Gartner   
1488   202201  J. Gouweleeuw    Jeffrey Gouweleeuw   
12170  244743      R. Prieto        Ronaldo Prieto   
3669   172233     P. Hetemaj      Perparim Hetemaj   
10163  224633        He Guan               Guan He   
7939   214411    N. Maturana      Nicolás Maturana   
18937  257372      A. Phelan           Alex Phelan   
8718   206147   M. Antonsson      Marcus Antonsson   
6073   191153    M. Sandberg       Marcus Sandberg   

                                               photoUrl  \
17329  https://cdn.sofifa.com/players/258/152/21_60.png   
11181  https://cdn.sofifa.com/players/199/768/21_60.png   
1488   https://cdn.sofifa.com/players/202/201/21_60.png   
12170  https://cdn.sofifa.com/players/244/743/21_60.png   
3669   https://cdn.sofifa.com/players/172/233/21_60.png   
10163  https://cdn.sofifa.com/players/224/633/21_60.png   
7939   https://cdn.sofifa.com/players/214/411/21_60.png   
18937  https://cdn.sofifa.com/players/257/372/21_60.png   
8718   https://cdn.sofifa.com/players/206/147/21_60.png   
6073   https://cdn.sofifa.com/players/191/153/21_60.png   

                                               playerUrl          Nationality  \
17329  http://sofifa.com/player/258152/nmadi-morris-i...              Germany   
11181  http://sofifa.com/player/199768/christian-gart...              Austria   
1488   http://sofifa.com/player/202201/jeffrey-gouwel...          Netherlands   
12170  http://sofifa.com/player/244743/ronaldo-prieto...               Mexico   
3669   http://sofifa.com/player/172233/perparim-hetem...              Finland   
10163    http://sofifa.com/player/224633/guan-he/210006/             China PR   
7939   http://sofifa.com/player/214411/nicolas-matura...                Chile   
18937  http://sofifa.com/player/257372/alex-phelan/21...  Republic of Ireland   
8718   http://sofifa.com/player/206147/marcus-antonss...               Sweden   
6073   http://sofifa.com/player/191153/marcus-sandber...               Sweden   

       Age  ↓OVA  POT                              Club  ...     A/W     D/W  \
17329   17    56   70             \n\n\n\nSV Sandhausen  ...  Medium    High   
11181   26    64   66  \n\n\n\nFC Admira Wacker Mödling  ...  Medium  Medium   
1488    28    76   76               \n\n\n\nFC Augsburg  ...    High  Medium   
12170   23    63   70             \n\n\n\nSantos Laguna  ...    High     Low   
3669    33    72   72                 \n\n\n\nBenevento  ...    High    High   
10163   27    65   68          \n\n\n\nShanghai SIPG FC  ...  Medium  Medium   
7939    26    67   67                 \n\n\n\nColo-Colo  ...    High     Low   
18937   19    48   56              \n\n\n\nWaterford FC  ...  Medium  Medium   
8718    29    66   66            \n\n\n\nStabæk Fotball  ...    High    High   
6073    29    69   71            \n\n\n\nStabæk Fotball  ...  Medium  Medium   

        IR PAC SHO  PAS DRI DEF PHY Hits  
17329  1 ★  67  32   42  57  54  56  NaN  
11181  1 ★  65  53   65  68  63  59    2  
1488   1 ★  71  58   66  63  79  75   22  
12170  1 ★  79  58   61  67  34  51    4  
3669   2 ★  73  64   72  73  70  76    8  
10163  1 ★  71  32   51  52  65  71    1  
7939   1 ★  75  60   65  69  45  57    6  
18937  1 ★  65  43   48  50  39  48  NaN  
8718   1 ★  78  65   57  64  42  75    1  
6073   1 ★  69  67   66  70  33  69    2  

[10 rows x 77 columns]

In [3]:
df.shape

(18979, 77)

# Data Cleaning

### Create a copy of DataFrame

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                18979 non-null  int64 
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64 
 7   ↓OVA              18979 non-null  int64 
 8   POT               18979 non-null  int64 
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64 
 16  Best Position     18979 non-null  object
 17  Joined      

In [5]:
fifa = df.copy()

fifa.sample(3)

ID       Name      LongName  \
10210  140423  J. Buxton   Jake Buxton   
13318  246863  F. Nmecha  Felix Nmecha   
11546  211881    Q. Moll   Quirin Moll   

                                               photoUrl  \
10210  https://cdn.sofifa.com/players/140/423/21_60.png   
13318  https://cdn.sofifa.com/players/246/863/21_60.png   
11546  https://cdn.sofifa.com/players/211/881/21_60.png   

                                               playerUrl Nationality  Age  \
10210  http://sofifa.com/player/140423/jake-buxton/21...     England   35   
13318  http://sofifa.com/player/246863/felix-nmecha/2...     England   19   
11546  http://sofifa.com/player/211881/quirin-moll/21...     Germany   29   

       ↓OVA  POT                      Club  ...     A/W     D/W   IR PAC SHO  \
10210    65   65     \n\n\n\nBurton Albion  ...     Low    High  1 ★  36  36   
13318    62   82   \n\n\n\nManchester City  ...    High  Medium  1 ★  74  54   
11546    64   64  \n\n\n\nTSV 1860 München  ...  Medium  Medium  1 ★  59  50   

       PAS DRI DEF PHY Hits  
10210   45  36  65  71    1  
13318   61  62  45  55  136  
11546   59  57  64  70    6  

[3 rows x 77 columns]

## 1. ID

#### Unique identifier for each player 

In [6]:
fifa['ID'].dtype

dtype('int64')

In [7]:
fifa['ID'].unique()

array([158023,  20801, 200389, ..., 252757, 243790, 252520])

In [8]:
fifa['ID'].duplicated().unique()

array([False])

In [9]:
fifa = fifa.set_index('ID')

fifa.sample(1)

Name         LongName  \
ID                                     
236830  Z. Youssouf  Zaydou Youssouf   

                                                photoUrl  \
ID                                                         
236830  https://cdn.sofifa.com/players/236/830/21_60.png   

                                                playerUrl Nationality  Age  \
ID                                                                           
236830  http://sofifa.com/player/236830/zaydou-youssou...      France   20   

        ↓OVA  POT                      Club     Contract  ...     A/W     D/W  \
ID                                                        ...                   
236830    71   82  \n\n\n\nAS Saint-Étienne  2019 ~ 2023  ...  Medium  Medium   

         IR PAC  SHO PAS DRI DEF PHY Hits  
ID                                         
236830  1 ★  66   57  71  74  64  70   50  

[1 rows x 76 columns]

# 2. Name

Player's name

In [10]:
fifa['Name'].dtype

dtype('O')

In [11]:
fifa['Name'].unique()

array(['L. Messi', 'Cristiano Ronaldo', 'J. Oblak', ..., 'R. McKinley',
       "Wang Zhen'ao", 'Zhou Xiao'], dtype=object)

## 3. Long Name of player

Player's full name

In [12]:
fifa['LongName'].dtype

dtype('O')

In [13]:
fifa['LongName'].unique()

array(['Lionel Messi', 'C. Ronaldo dos Santos Aveiro', 'Jan Oblak', ...,
       'Ronan McKinley', "Zhen'ao Wang", 'Xiao Zhou'], dtype=object)

# 4. photoURL

URL to player's photo

In [14]:
fifa['photoUrl'].dtype

dtype('O')

In [15]:
fifa['photoUrl'].unique()

array(['https://cdn.sofifa.com/players/158/023/21_60.png',
       'https://cdn.sofifa.com/players/020/801/21_60.png',
       'https://cdn.sofifa.com/players/200/389/21_60.png', ...,
       'https://cdn.sofifa.com/players/252/757/21_60.png',
       'https://cdn.sofifa.com/players/243/790/21_60.png',
       'https://cdn.sofifa.com/players/252/520/21_60.png'], dtype=object)

# 5. playerURL

URL to player's profile

In [16]:
fifa['playerUrl'].dtype

dtype('O')

In [17]:
fifa['playerUrl'].unique()

array(['http://sofifa.com/player/158023/lionel-messi/210006/',
       'http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210006/',
       'http://sofifa.com/player/200389/jan-oblak/210006/', ...,
       'http://sofifa.com/player/252757/ronan-mckinley/210006/',
       'http://sofifa.com/player/243790/zhenao-wang/210006/',
       'http://sofifa.com/player/252520/xiao-zhou/210006/'], dtype=object)

# 6. Nationality

Player's nationality

In [18]:
fifa['Nationality'].dtype

dtype('O')

In [19]:
fifa['Nationality'].unique()

array(['Argentina', 'Portugal', 'Slovenia', 'Belgium', 'Brazil', 'Poland',
       'Egypt', 'France', 'Germany', 'Netherlands', 'Senegal', 'Spain',
       'England', 'Scotland', 'Korea Republic', 'Costa Rica', 'Italy',
       'Gabon', 'Croatia', 'Uruguay', 'Switzerland', 'Serbia', 'Slovakia',
       'Morocco', 'Algeria', 'Denmark', 'Hungary', 'Bosnia Herzegovina',
       'Nigeria', 'Cameroon', 'Norway', 'Ghana', 'Mexico', 'Austria',
       'Albania', 'Colombia', 'Chile', 'Ivory Coast', 'Greece', 'Finland',
       'Wales', 'Sweden', 'Togo', 'Czech Republic', 'Russia', 'Venezuela',
       'Canada', 'United States', 'Guinea', 'Montenegro', 'Israel',
       'Republic of Ireland', 'Ukraine', 'Turkey', 'Ecuador', 'Jamaica',
       'DR Congo', 'Australia', 'China PR', 'Armenia', 'Northern Ireland',
       'North Macedonia', 'Kosovo', 'Mali', 'Peru',
       'Central African Republic', 'Iceland', 'Burkina Faso', 'Paraguay',
       'Japan', 'Romania', 'New Zealand', 'Iran', 'Angola', 'Tunisia',
 

# 7. Age

Player's age in years

In [20]:
fifa['Age'].dtype

dtype('int64')

In [21]:
fifa['Age'].unique()

array([33, 35, 27, 29, 28, 31, 21, 34, 32, 25, 26, 30, 20, 24, 22, 23, 19,
       38, 42, 36, 37, 18, 17, 39, 40, 41, 16, 43, 53])

# 8. OVA - Overall Rating (0-100)

It is a rating system used to represent a player's overall abilities and skills in the game. 

In [22]:
fifa['↓OVA'].dtype

dtype('int64')

In [23]:
fifa['↓OVA'].unique()

array([93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77,
       76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,
       59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47])

# 9. POT - Potential Rating(0 - 100)

Represent a player's potential to develop and improve their abilities and skills over time

In [24]:
fifa['POT'].dtype

dtype('int64')

In [25]:
fifa['POT'].unique()

array([93, 92, 91, 90, 95, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78,
       77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61,
       60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47])

## 10. Club

Current Club of the player

In [26]:
fifa['Club'].dtype

dtype('O')

In [27]:
fifa['Club'].unique()

array(['\n\n\n\nFC Barcelona', '\n\n\n\nJuventus',
       '\n\n\n\nAtlético Madrid', '\n\n\n\nManchester City',
       '\n\n\n\nParis Saint-Germain', '\n\n\n\nFC Bayern München',
       '\n\n\n\nLiverpool', '\n\n\n\nReal Madrid', '\n\n\n\nChelsea',
       '\n\n\n\nTottenham Hotspur', '\n\n\n\nInter', '\n\n\n\nNapoli',
       '\n\n\n\nBorussia Dortmund', '\n\n\n\nManchester United',
       '\n\n\n\nArsenal', '\n\n\n\nLazio', '\n\n\n\nLeicester City',
       '\n\n\n\nBorussia Mönchengladbach', '\n\n\n\nReal Sociedad',
       '\n\n\n\nAtalanta', '\n\n\n\nOlympique Lyonnais', '\n\n\n\nMilan',
       '\n\n\n\nVillarreal CF', '\n\n\n\nRB Leipzig', '\n\n\n\nCagliari',
       '\n\n\n\nAjax', '\n\n\n\nSL Benfica', '\n\n\n\nAS Monaco',
       '\n\n\n\nWolverhampton Wanderers', '\n\n\n\nEverton',
       '\n\n\n\nFiorentina', '\n\n\n\nFC Porto', '\n\n\n\nRC Celta',
       '\n\n\n\nTorino', '\n\n\n\nSevilla FC', '\n\n\n\nGrêmio',
       '\n\n\n\nReal Betis', '\n\n\n\nRoma', '\n\n\n\nNewcastle Unite

In [28]:
fifa['Club'] = fifa['Club'].str.strip()

In [29]:
fifa['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sino

## 11. Contract

Player's contract details

In [30]:
fifa['Contract'].dtype

dtype('O')

In [31]:
fifa['Contract'].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 

In [32]:
for index, row in fifa.iterrows():
    if "Free" in row['Contract'] or "On Loan" in row['Contract']:
        print(row['Contract'])

Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Free
Free
Free
Free
Free
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Free
Free
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Free
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jan 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Free
Free

Free
Dec 31, 2021 On Loan
Dec 31, 2020 On Loan
Free
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jan 31, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jan 31, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan


Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 23, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jan 31, 2021 On Loan
Jun 30, 2021 On Loan
Nov 27, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Free
Dec 31, 2020 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jan 1, 2021 On Loan
Nov 30, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jan 1, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Nov 30, 2020 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Free
Free
Ju

#### A. start_date & end_date & duration in years

In [33]:
def extract_contract_info(contract):
    if contract == "Free" or "On Loan" in contract:
        start_date = np.nan
        end_date = np.nan
        contract_length = 0
    else:
        start_date, end_date =  contract.split(" ~ ")
        start_year = int(start_date[:4])
        end_year = int(end_date[:4])
        contract_length = end_year - start_year
    
    return start_date, end_date, contract_length

In [34]:
new_cols = ['Contract Start', 'Contract End', "Contract Length(years)"]

new_data = fifa['Contract'].apply(lambda x : pd.Series(extract_contract_info(x)))

for i in range(len(new_cols)):
    fifa.insert(loc=fifa.columns.get_loc('Contract') + 1 + i, 
                column=new_cols[i],
                value=new_data[i]
               )

    

In [35]:
pd.set_option('display.max_columns', None)
fifa.sample(3)

Name           LongName  \
ID                                          
206631         K. Rowe         Kelyn Rowe   
231247        B. Cufré       Braian Cufré   
192449  M. Stiepermann  Marco Stiepermann   

                                                photoUrl  \
ID                                                         
206631  https://cdn.sofifa.com/players/206/631/21_60.png   
231247  https://cdn.sofifa.com/players/231/247/21_60.png   
192449  https://cdn.sofifa.com/players/192/449/21_60.png   

                                                playerUrl    Nationality  Age  \
ID                                                                              
206631  http://sofifa.com/player/206631/kelyn-rowe/210...  United States   28   
231247  http://sofifa.com/player/231247/braian-cufre/2...      Argentina   23   
192449  http://sofifa.com/player/192449/marco-stieperm...        Germany   29   

        ↓OVA  POT                    Club     Contract Contract Start  \
ID                                                                      
206631    65   65  New England Revolution  2019 ~ 2020           2019   
231247    74   81            RCD Mallorca  2020 ~ 2024           2020   
192449    71   71            Norwich City  2017 ~ 2022           2017   

       Contract End  Contract Length(years)    Positions Height Weight  \
ID                                                                       
206631         2020                     1.0  CM, CAM, LB  173cm   68kg   
231247         2024                     4.0      LB, LWB  179cm   82kg   
192449         2022                     5.0          CAM  190cm   86kg   

       Preferred Foot  BOV Best Position     Joined Loan Date End  Value Wage  \
ID                                                                              
206631          Right   65            CM  04-Dec-19           NaN  €725K  €2K   
231247           Left   76           LWB  28-Sep-20           NaN    €8M  €7K   
192449           Left   72            CM  06-Aug-17           NaN  €1.8M  €9K   

       Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
ID                                                                        
206631          €788K        295        67         58                52   
231247         €12.6M        323        76         58                58   
192449          €4.4M        334        67         67                64   

        Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  \
ID                                                                     
206631             68       50    332         67     69           66   
231247             72       59    368         75     83           66   
192449             71       65    355         74     73           67   

        Long Passing  Ball Control  Movement  Acceleration  Sprint Speed  \
ID                                                                         
206631            65            65       332            60            62   
231247            70            74       374            80            83   
192449            68            73       319            61            68   

        Agility  Reactions  Balance  Power  Shot Power  Jumping  Stamina  \
ID                                                                         
206631       68         65       77    326          72       64       66   
231247       82         67       62    386          82       80       89   
192449       61         75       54    369          84       52       85   

        Strength  Long Shots  Mentality  Aggression  Interceptions  \
ID                                                                   
206631        60          64        316          62             61   
231247        70          65        318          70             68   
192449        76          72        342          78             62   

        Positioning  Vision  Penalties  Composure  Defending  Marking  \
ID                 

In [36]:
fifa[['Contract',
      'Contract Start',
      'Contract End',
      "Contract Length(years)"
     ]].sample(3)

Contract Contract Start Contract End  Contract Length(years)
ID                                                                     
243319  2018 ~ 2021           2018         2021                     3.0
246885  2019 ~ 2021           2019         2021                     2.0
242920  2020 ~ 2022           2020         2022                     2.0

#### B. Contract categories

In [37]:
def categorize_contract_status(contract):
    if contract == "Free":
        return 'Free'
    elif 'On Loan' in contract:
        return 'On Loan'
    else:
        return 'Contract'

In [38]:
new_data = fifa['Contract'].apply(categorize_contract_status)
fifa.insert(fifa.columns.get_loc('Contract Length(years)') + 1,
            'Contract Status',
            new_data
           )

fifa.sample(3)

Name      LongName  \
ID                                
258797    A. Yoda   Abdoul Yoda   
177129  A. Bodzek   Adam Bodzek   
233743   B. Tabla  Ballou Tabla   

                                                photoUrl  \
ID                                                         
258797  https://cdn.sofifa.com/players/258/797/21_60.png   
177129  https://cdn.sofifa.com/players/177/129/21_60.png   
233743  https://cdn.sofifa.com/players/233/743/21_60.png   

                                                playerUrl   Nationality  Age  \
ID                                                                             
258797  http://sofifa.com/player/258797/abdoul-yoda/21...  Burkina Faso   19   
177129  http://sofifa.com/player/177129/adam-bodzek/21...        Poland   34   
233743  http://sofifa.com/player/233743/ballou-tabla/2...        Canada   21   

        ↓OVA  POT                Club     Contract Contract Start  \
ID                                                                  
258797    55   70        TSV Hartberg  2020 ~ 2022           2020   
177129    70   70  Fortuna Düsseldorf  2011 ~ 2021           2011   
233743    63   74     Montreal Impact  2020 ~ 2021           2020   

       Contract End  Contract Length(years) Contract Status   Positions  \
ID                                                                        
258797         2022                     2.0        Contract          CM   
177129         2021                    10.0        Contract     CDM, CM   
233743         2021                     1.0        Contract  LM, LW, RM   

       Height Weight Preferred Foot  BOV Best Position     Joined  \
ID                                                                  
258797  182cm   75kg          Right   57           CAM  11-Sep-20   
177129  184cm   80kg          Right   70           CDM  01-Jan-11   
233743  174cm   69kg          Right   65           CAM  16-Jan-20   

       Loan Date End  Value  Wage Release Clause  Attacking  Crossing  \
ID                                                                      
258797           NaN  €300K  €800          €353K        220        41   
177129           NaN  €550K  €14K          €1.1M        280        49   
233743           NaN  €1.1M   €1K            €1M        273        59   

        Finishing  Heading Accuracy  Short Passing  Volleys  Skill  Dribbling  \
ID                                                                              
258797         32                52             58       37    246         60   
177129         48                61             68       54    301         57   
233743         53                43             63       55    316         73   

        Curve  FK Accuracy  Long Passing  Ball Control  Movement  \
ID                                                                 
258797     32           35            57            62       311   
177129     61           59            65            59       259   
233743     69           54            54            66       381   

        Acceleration  Sprint Speed  Agility  Reactions  Balance  Power  \
ID                                                                       
258797            66            67       69         39       70    293   
177129            41            34       53         69       62    353   
233743            83            75       91         52       80    245   

        Shot Power  Jumping  Stamina  Strength  Long Shots  Mentality  \
ID                                                                      
258797          52       68       67        61          45        244   
177129          66       83       67        78          59        300   
233743          66       33       39        41          66        251   

        Aggression  Interceptions  Positioning  Vision  Penalties  Composure  \
ID                                                                             
258797          61             48           48      55   

In [39]:
fifa[['Contract',
      'Contract Start',
      'Contract End',
      "Contract Length(years)",
      "Contract Status"
     ]].sample(3)

Contract Contract Start Contract End  Contract Length(years)  \
ID                                                                        
213746  2019 ~ 2020           2019         2020                     1.0   
176585  2020 ~ 2020           2020         2020                     0.0   
230273  2019 ~ 2023           2019         2023                     4.0   

       Contract Status  
ID                      
213746        Contract  
176585        Contract  
230273        Contract

# 12. Positions

Player's preferred position on the field

In [40]:
fifa['Positions'].dtype

dtype('O')

In [41]:
fifa['Positions'].unique()

array(['RW, ST, CF', 'ST, LW', 'GK', 'CAM, CM', 'LW, CAM', 'ST', 'RW',
       'ST, LW, RW', 'CB', 'LW', 'CDM', 'CF, ST', 'LW, RW', 'CDM, CM',
       'CDM, RB', 'CF, CAM', 'LW, ST', 'CM', 'ST, CF, LW', 'RM, LM, CAM',
       'RB', 'RW, CAM, CM', 'LB', 'LM, CF', 'CF', 'RW, LW', 'CAM, RM, RW',
       'CM, CDM', 'CAM, CF, ST', 'CM, CDM, CAM', 'CF, LW, CAM',
       'CAM, RM, CF', 'LM, ST', 'RM, LM, RW', 'LM', 'CAM, RW', 'CB, CDM',
       'RW, RM', 'LW, CF', 'CM, RM, LM', 'LB, LM', 'CAM, CM, RM',
       'CAM, CM, CF', 'CAM, CF', 'LM, RM, LW', 'LM, LB, CM', 'CM, LM, LB',
       'RM, RW', 'RM, CM', 'CAM, CM, LW', 'CB, LB', 'RM, RB', 'ST, RW',
       'LM, RW, LW', 'RB, LB', 'RB, RM', 'RM', 'LM, RM, CF', 'CAM, RM',
       'RB, RWB', 'CDM, CB, CM', 'CAM, RM, ST', 'LM, LW, RM', 'CM, CAM',
       'ST, RM, CF', 'LM, RM', 'RM, CF', 'LM, LWB', 'RW, RM, CF',
       'RB, CM', 'LW, CAM, RW', 'CAM, LW, CM', 'CM, CAM, CDM',
       'RW, LW, CAM', 'CM, CAM, LM', 'CM, RM, ST', 'CDM, CM, RB',
       'ST, CAM', 

# 13. Height

Player's height in cm

In [42]:
fifa['Height'].dtype

dtype('O')

In [43]:
fifa['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [44]:
def convert_height(height: str) -> int:
    if "cm" in height:
        return int(height.strip("cm"))
    else:
        feet, inches = height.split("\'")
        total_inches = int(feet) * 12 + int(inches.strip("\""))
        return round(total_inches * 2.54)

In [45]:
fifa['Height'] = fifa['Height'].apply(convert_height)

fifa['Height'].sample(3)

ID
222717    167
226724    176
238014    179
Name: Height, dtype: int64

In [46]:
fifa['Height'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 201,
       158, 162, 161, 160, 203, 157, 156, 202, 159, 206, 155])

In [47]:
fifa = fifa.rename(columns={'Height' : 'Height(cm)'})
fifa.sample(1)

Name      LongName  \
ID                              
229701  P. Ochs  Philipp Ochs   

                                                photoUrl  \
ID                                                         
229701  https://cdn.sofifa.com/players/229/701/21_60.png   

                                                playerUrl Nationality  Age  \
ID                                                                           
229701  http://sofifa.com/player/229701/philipp-ochs/2...     Germany   23   

        ↓OVA  POT         Club     Contract Contract Start Contract End  \
ID                                                                        
229701    64   71  Hannover 96  2020 ~ 2022           2020         2022   

        Contract Length(years) Contract Status   Positions  Height(cm) Weight  \
ID                                                                              
229701                     2.0        Contract  LB, CM, ST         175   75kg   

       Preferred Foot  BOV Best Position     Joined Loan Date End  Value Wage  \
ID                                                                              
229701           Left   68            LM  31-Jan-20           NaN  €1.1M  €5K   

       Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
ID                                                                        
229701            €1M        305        68         62                54   

        Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  \
ID                                                                     
229701             68       53    322         69     60           64   

        Long Passing  Ball Control  Movement  Acceleration  Sprint Speed  \
ID                                                                         
229701            60            69       359            73            68   

        Agility  Reactions  Balance  Power  Shot Power  Jumping  Stamina  \
ID                                                                         
229701       76         59       83    324          75       69       66   

        Strength  Long Shots  Mentality  Aggression  Interceptions  \
ID                                                                   
229701        58          56        293          57             56   

        Positioning  Vision  Penalties  Composure  Defending  Marking  \
ID                                                                      
229701           59      56         65         58        170       57   

        Standing Tackle  Sliding Tackle  Goalkeeping  GK Diving  GK Handling  \
ID                                                                             
229701               57              56           49          9           10   

        GK Kicking  GK Positioning  GK Reflexes  Total Stats  Base Stats  W/F  \
ID                                                                              
229701           6              11           13         1822         383  3 ★   

        SM   A/W     D/W   IR  PAC  SHO  PAS  DRI  DEF  PHY Hits  
ID                                                                
229701  3★  High  Medium  1 ★   70   63   64   70   56   60   25

# 14. Weight 

Player's weight in kg

In [48]:
fifa['Weight'].dtype

dtype('O')

In [49]:
fifa['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [50]:
def convert_weight(weight: str) -> int:
    if "kg" in weight:
        return int(weight.strip("kg"))
    else:
        pounds = int(weight.strip("lbs"))
        return round(pounds/2.205)

In [51]:
fifa['Weight'] = fifa['Weight'].apply(convert_weight)
fifa['Weight'].unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99, 102,  56, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52])

In [52]:
fifa = fifa.rename(columns={"Weight" : "Weight(kg)"})

# 15. Preferred Foot

Player's preferred foot - Left or Right

In [53]:
fifa['Preferred Foot'].dtype

dtype('O')

In [54]:
fifa['Preferred Foot'].unique()

array(['Left', 'Right'], dtype=object)

# 16. BOV

Best Overall Rating of the Player in a specific position

In [55]:
fifa['BOV'].dtype

dtype('int64')

In [56]:
fifa['BOV'].unique()

array([93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77,
       76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,
       59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48])

# 17. Best Position

Player's best position on the field

In [57]:
fifa['Best Position'].dtype

dtype('O')

In [58]:
fifa['Best Position'].unique()

array(['RW', 'ST', 'GK', 'CAM', 'LW', 'CB', 'CDM', 'CF', 'CM', 'RB', 'LB',
       'LM', 'RM', 'LWB', 'RWB'], dtype=object)

# 18. Joined

Date when the player joined the current club

In [59]:
fifa['Joined'].dtype

dtype('O')

In [60]:
fifa['Joined'].unique()

array(['01-Jul-04', '10-Jul-18', '16-Jul-14', ..., '22-Sep-18',
       '28-Feb-15', '06-Mar-18'], dtype=object)

# 19. Loan Date End

Date when the player's loan ends (if On Loan)

In [61]:
fifa['Loan Date End'].dtype

dtype('O')

In [62]:
fifa['Loan Date End'].unique()

array([nan, '30-Jun-21', '31-Dec-20', '30-Jan-21', '30-Jun-22',
       '31-May-21', '05-Jul-21', '31-Dec-21', '01-Jul-21', '01-Jan-21',
       '31-Aug-21', '31-Jan-21', '30-Dec-21', '23-Jun-21', '03-Jan-21',
       '27-Nov-21', '17-Jan-21', '30-Jun-23', '31-Jul-21', '22-Nov-20',
       '31-May-22', '30-Dec-20', '04-Jan-21', '30-Nov-20', '01-Aug-21'],
      dtype=object)

In [63]:
fifa["Loan Date End"] = fifa['Loan Date End'].fillna("")

In [64]:
fifa['Loan Date End'].unique()

array(['', '30-Jun-21', '31-Dec-20', '30-Jan-21', '30-Jun-22',
       '31-May-21', '05-Jul-21', '31-Dec-21', '01-Jul-21', '01-Jan-21',
       '31-Aug-21', '31-Jan-21', '30-Dec-21', '23-Jun-21', '03-Jan-21',
       '27-Nov-21', '17-Jan-21', '30-Jun-23', '31-Jul-21', '22-Nov-20',
       '31-May-22', '30-Dec-20', '04-Jan-21', '30-Nov-20', '01-Aug-21'],
      dtype=object)

# 20. Value

Estimated market value of the player

In [65]:
fifa['Value'].dtype

dtype('O')

In [66]:
fifa['Value'].unique()

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '

In [67]:
def convert_value(value: str) :
    
    nb_str =  value.strip("K|M|€")
    if "K" in value:
        return float(nb_str)
    return float(nb_str) * 1000

In [68]:
fifa['Value'] = fifa['Value'].apply(convert_value)

In [69]:
fifa = fifa.rename(columns={"Value" : "Value (1 = 1000 €)"})

In [70]:
fifa.sample(3)

Name        LongName  \
ID                                  
204485  R. Mahrez    Riyad Mahrez   
183498  M. Parolo    Marco Parolo   
190424     E. Adu  Enoch Kofi Adu   

                                                photoUrl  \
ID                                                         
204485  https://cdn.sofifa.com/players/204/485/21_60.png   
183498  https://cdn.sofifa.com/players/183/498/21_60.png   
190424  https://cdn.sofifa.com/players/190/424/21_60.png   

                                                playerUrl Nationality  Age  \
ID                                                                           
204485  http://sofifa.com/player/204485/riyad-mahrez/2...     Algeria   29   
183498  http://sofifa.com/player/183498/marco-parolo/2...       Italy   35   
190424  http://sofifa.com/player/190424/enoch-kofi-adu...       Ghana   29   

        ↓OVA  POT             Club     Contract Contract Start Contract End  \
ID                                                                            
204485    85   85  Manchester City  2018 ~ 2023           2018         2023   
183498    79   79            Lazio  2014 ~ 2021           2014         2021   
190424    68   68              AIK  2018 ~ 2020           2018         2020   

        Contract Length(years) Contract Status Positions  Height(cm)  \
ID                                                                     
204485                     5.0        Contract    RW, RM         179   
183498                     7.0        Contract   CDM, CM         184   
190424                     2.0        Contract   CDM, CM         178   

        Weight(kg) Preferred Foot  BOV Best Position     Joined Loan Date End  \
ID                                                                              
204485          67           Left   85            RW  10-Jul-18                 
183498          75          Right   79           CDM  01-Jul-14                 
190424          67          Right   68           CDM  01-Jan-18                 

        Value (1 = 1000 €)   Wage Release Clause  Attacking  Crossing  \
ID                                                                      
204485             53000.0  €210K         €69.4M        366        83   
183498              4900.0   €40K          €6.8M        369        70   
190424              1000.0    €4K          €969K        227        56   

        Finishing  Heading Accuracy  Short Passing  Volleys  Skill  Dribbling  \
ID                                                                              
204485         79                48             80       76    418         90   
183498         70                75             78       76    354         75   
190424         35                35             70       31    331         67   

        Curve  FK Accuracy  Long Passing  Ball Control  Movement  \
ID                                                                 
204485     84           78            75            91       427   
183498     67           55            79            78       330   
190424     67           55            71            71       341   

        Acceleration  Sprint Speed  Agility  Reactions  Balance  Power  \
ID                                                                       
204485            87            79       92         81       88    350   
183498            64            52       63         80       71    392   
190424            59            45       85         69       83    299   

        Shot Power  Jumping  Stamina  Strength  Long Shots  Mentality  \
ID                                                                      
204485          79       60       76        55          80        321   
183498          87       77       75        69          84        365   
190424          52       67       73        58          49        282   

        Aggression  Interceptions  Positioning  Vision  Penalties  Composure  \
ID                                        

# 21 Wage

Weekly wage of the player

In [71]:
fifa["Wage"].dtype

dtype('O')

In [72]:
fifa["Wage"].unique()

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€5

In [73]:
def convert_wage(wage: str) -> int :
    if "K" in wage:
        return int(wage.strip("K|€")) * 1000
    return int(wage.strip("€"))

In [74]:
fifa["Wage"] = fifa["Wage"].apply(convert_wage)

In [75]:
fifa["Wage"].unique()

array([560000, 220000, 125000, 370000, 270000, 240000, 250000, 160000,
       260000, 210000, 310000, 130000, 350000, 300000, 190000, 145000,
       195000, 100000, 140000, 290000,  82000, 110000, 230000, 155000,
       200000, 165000,  95000, 170000, 105000, 115000, 150000, 135000,
        55000,  58000,  81000,  34000, 120000,  59000,  90000,  65000,
        56000,  71000,  18000,  75000,  47000,  20000,  84000,  86000,
        74000,  78000,  27000,  68000,  85000,  25000,  46000,  83000,
        54000,  79000, 175000,  43000,  49000,  45000,  38000,  41000,
        39000,  23000,  51000,  50000,  87000,  30000,  14000,  69000,
        31000,  64000,  53000,  35000,  21000,  28000,  17000,  33000,
        70000,  32000,  89000,  26000,  40000,  76000,  72000,  48000,
        36000,  29000,  60000,  16000,  37000,  24000,  52000,      0,
        62000,  73000,  63000,  19000,   1000,  66000,  80000,  12000,
         2000,  42000,  13000,    900,  57000,  77000,  61000,  22000,
      

# 22. Release Clause

Release clause in the player's contract

In [76]:
fifa["Release Clause"].dtype

dtype('O')

In [77]:
fifa["Release Clause"].unique()

array(['€138.4M', '€75.9M', '€159.4M', ..., '€59K', '€35K', '€64K'],
      dtype=object)

In [78]:
fifa["Release Clause"] = fifa["Release Clause"].apply(convert_value)

In [79]:
fifa["Release Clause"].sample(10)

ID
243357     2200.0
250941     2800.0
173665      140.0
251742        0.0
238336     2000.0
257720      135.0
234827        0.0
205553     5400.0
219244    11900.0
257568      161.0
Name: Release Clause, dtype: float64

In [80]:
fifa = fifa.rename(columns={"Release Clause" : "Release Clause (1000€)"})

# 23. Attacking

Composite rating in the player's contract

In [81]:
fifa["Attacking"].dtype

dtype('int64')

In [82]:
fifa["Attacking"].unique()

array([429, 437,  95, 407, 408, 423, 392, 114, 118, 316, 410, 349,  86,
       119, 426, 374, 411, 360, 328, 383, 405, 123, 420, 224, 388, 397,
       425, 373, 365, 371, 311, 396, 345, 399, 400,  78, 280, 330, 403,
       379, 380,  94, 394, 419, 339, 293, 344, 390,  84, 359, 372, 377,
       346, 389, 386, 308, 277, 382, 368, 402, 292, 298, 366, 352, 363,
       322, 361,  91, 364, 341, 385, 355, 305, 321, 262,  93, 375, 387,
       356, 253, 285, 391, 353, 367,  90, 295, 378, 256, 338, 331,  69,
       105,  85, 358, 343, 319, 271, 113, 350, 406, 340, 393, 247, 334,
       351, 342, 302, 329, 354,  98, 301, 115, 384, 208,  72, 376,  92,
       258, 362,  74, 417,  99, 263,  88, 279, 101, 395, 100,  81,  87,
        55, 310,  82, 117, 409, 318, 323, 248, 315, 381, 348, 327, 309,
       130, 283, 336, 369, 106, 252, 320, 290, 370, 126, 251, 108, 335,
       297, 284,  80,  75, 357, 270,  97, 306, 337,  73, 286, 325, 326,
       324, 333, 103, 259, 273, 313, 296,  61, 312, 347, 401, 30

# 24. Crossing

Player's ability to make accurate crosses.

In [83]:
fifa["Crossing"].dtype

dtype('int64')

In [84]:
fifa["Crossing"].unique()

array([85, 84, 13, 94, 71, 79, 17, 78, 18, 53, 76, 58, 14, 15, 75, 66, 70,
       68, 91, 82, 20, 12, 30, 77, 88, 83, 93, 90, 87, 81, 73, 11, 54, 62,
       86, 80, 55, 42, 57, 65, 63, 64, 52, 40, 69, 47, 60,  9, 16, 44, 72,
       50, 56, 46, 89, 34, 45, 74, 49, 67, 24, 35, 36, 61, 19, 27, 25, 10,
       51, 38, 43, 59, 39, 48, 23,  8, 28, 92, 41, 29, 32, 22, 26, 37, 33,
       31, 21,  7,  6])

# 25. Finishing

Player's ability to score goals

In [85]:
fifa["Finishing"].dtype

dtype('int64')

In [86]:
fifa["Finishing"].unique()

array([95, 11, 82, 87, 94, 91, 13, 14, 52, 90, 64, 88, 65, 85, 66, 84, 10,
       22, 76, 81, 56, 79, 57, 45, 77, 63, 86, 80, 15, 33, 67, 12, 72, 92,
       93, 51, 46, 60, 75, 55, 73, 83, 50, 42, 39, 40,  9, 68, 48, 37, 70,
       78, 69,  8, 53, 89, 25, 62, 71, 74, 44, 26, 19, 32, 18, 61, 58, 30,
       54, 36, 29, 16, 38, 59, 27, 34, 47, 20, 31, 49, 43, 41, 28,  5,  7,
        6, 21, 17, 35, 23, 24,  4,  3])

# 26. Heading Accuracy

Player's ability to win aerial duels.

In [87]:
fifa["Heading Accuracy"].dtype

dtype('int64')

# 27. Short Passing

Player's ability to make short passes accurately.

In [88]:
fifa["Short Passing"].dtype

dtype('int64')

# 28. Volleys

Player's ability to take volleys

In [89]:
fifa["Volleys"].dtype

dtype('int64')

# 29. Skill

Composite rating of the player's technical abilities.

In [90]:
fifa["Skill"].dtype

dtype('int64')

# 30. Dribbling

Player's ability to dribble past defenders.


In [91]:
fifa["Dribbling"].dtype

dtype('int64')

# 31. Curve

Player's ability to curve the ball.

In [92]:
fifa["Curve"].dtype

dtype('int64')

# 32. FK Accuracy

Player's ability to take free kicks.

In [93]:
fifa["FK Accuracy"].dtype

dtype('int64')

# 33. Long Passing

Player's ability to make long passes accurately.

In [94]:
fifa["Long Passing"].dtype

dtype('int64')

# 34. Ball Control

Player's ability to control the ball.

In [95]:
fifa["Ball Control"].dtype

dtype('int64')

# 35. Movement

Composite rating of the player's movement abilities.

In [96]:
fifa["Movement"].dtype

dtype('int64')

# 36. Acceleration

Player's ability to accelerate quickly.

In [97]:
fifa["Acceleration"].dtype

dtype('int64')

# 37. Sprint Speed

Player's top speed

In [98]:
fifa["Sprint Speed"].dtype

dtype('int64')

# 38. Agility

Player's agility

In [99]:
fifa["Agility"].dtype

dtype('int64')

# 39. Reactions

Player's reaction time

In [100]:
fifa["Reactions"].dtype

dtype('int64')

# 40. Balance

Player's balance

In [101]:
fifa["Balance"].dtype

dtype('int64')

# 41. Power

Composite rating of player's physical abilities

In [102]:
fifa["Power"].dtype

dtype('int64')

# 42. Shoot Power

Player's ability to shoot with power

In [103]:
fifa["Shot Power"].dtype

dtype('int64')

# 66. W/F

Player's weak foot rating (out of 5)

In [104]:
fifa["W/F"].dtype

dtype('O')

In [105]:
fifa["W/F"].unique()

array(['4 ★', '3 ★', '5 ★', '2 ★', '1 ★'], dtype=object)

In [106]:
fifa["W/F"] = fifa["W/F"].str.replace('★', '')
fifa["W/F"].unique()

array(['4 ', '3 ', '5 ', '2 ', '1 '], dtype=object)

In [107]:
fifa["W/F"] = fifa["W/F"].str.rstrip(" ")

In [108]:
fifa["W/F"].unique()

array(['4', '3', '5', '2', '1'], dtype=object)

# 77. Hits

Number of times the player has been searched for in the FIFA database

In [109]:
fifa['Hits'].dtype

dtype('O')

In [110]:
fifa['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79',